*Yessenia Loayza
*Coloco labela a algunas var de interes.

label var 	OFICIO	"¿Qué hace……en este trabajo? "
*label var 	P6380	"¿Cuál es el nombre de la empresa, negocio, industria, oficina,  firma o finca donde trabaja…..?"
label var 	RAMA2D	"¿A qué actividad se dedica principalmente la empresa o negocio  en la que…… realiza su trabajo?"
label var 	P6440	"¿Para realizar este trabajo tiene ... algún tipo de contrato?"
label var 	P6450	"¿El contrato es verbal o escrito?"
label var 	P6460	"¿El contrato de trabajo es a termino indefinido o a termino fijo?"
label var 	P6465S1	"¿Por este contrato, le descontaron o pago ...:"
label var 	P6660S1	"¿Paga o le descuentan  mensualmente por:"
label var 	P6400	"La empresa o persona que contrató a ...., ¿es la misma empresa donde trabaja o  presta sus servicios?"
label var 	P6422	"¿Esta ..... Conforme  con el tipo de contrato  que tiene?"
label var 	P6424S1	"¿Por su contrato actual, recibe:"
label var 	P6426	"¿Cuanto tiempo lleva ... trabajando en esta empresa, negocio, industria, oficina,  firma o finca de manera continua?"
label var 	P6430	"En este trabajo…..es: "
label var 	P6480	"¿Por qué medio principal, .... consiguió su empleo actual?"
label var 	P6490	"¿Cuál es la razón principal por la que trabaja  como empleado en lugar de ser independiente?"
label var 	P6500	"Antes de descuentos ¿cuánto ganó .... el mes pasado en este empleo?"
label var 	P6510	"El mes pasado recibió ingresos por   concepto de horas extras?"
label var 	P6590	"Además del salario en dinero,¿el mes pasado recibió alimentos como parte de pago por su trabajo?"
label var 	P6600	"Además del salario en dinero,¿el mes pasado recibió vivienda como parte de pago por su trabajo?  "
label var 	P6610	"¿Normalmente... utiliza transporte de la empresa para desplazarse  a su trabajo (bus o automóvil)?"
label var 	P6620	"Además del salario en dinero, ¿el mes pasado... recibió otros ingresos en especie por su trabajo (electrodomésticos,ropa, productos diferentes aalimentos o bonos tipo Sodexho)?"
label var 	P6585S1	"¿Cuál  o cuáles de los siguientes subsidios recibió ..  el mes pasado: "
label var 	P6530	"¿El mes pasado recibió ingresos por gastos de representación?"
label var 	P6540	"El  mes pasado recibió ...:"
label var 	P6625	"¿Le descuentan mensualmente por fondo de  solidaridad pensional?"
label var 	P6630S1	"En los últimos 12 meses recibió:"
label var 	P6640	"¿La semana pasada ..... trabajó horas extras remuneradas?"
label var 	P6642S1	"¿En que horario y cuantas  horas extras?"
label var 	P7650	"¿Trabajó alguna vez como independiente (cuenta propia, patrón o empleador), en su ocupación principal, por lo menos un año?"
label var 	P7660	"¿Cuándo fue la última vez que trabajó como independiente?"
label var 	P7670	"¿Cuál fue la razón principal por la que se terminó este trabajo?"
label var 	P7680	"Además de su trabajo actual, ¿Trabajó alguna vez como asalariado con prestaciones, en su ocupación principal, por lo menos un año?"
label var 	P7690	"Además de su trabajo actual,  ¿Cuándo fue la ultima vez que trabajó como asalariado con prestaciones?"
label var 	P7700	"¿Cuál fue la razón principal por la que se terminó este trabajo?"
label var 	P7710	"Además de su trabajo actual, ¿Trabajó alguna vez como asalariado sin prestaciones, en su ocupación principal, por lo menos un año?"
label var 	P7720	"Además de su trabajo actual, ¿Cuándo fue la ultima vez que trabajó como asalariado sin prestaciones?"
label var 	P7730	"¿Cuál fue la razón principal por la que se terminó este trabajo?"
label var 	P6765	"En la semana pasada, ¿cuál de las siguientes formas de trabajo realizó:"
label var 	P6772	"¿ ..... ha registrado el negocio ante alguna autoridad o ante alguna entidad? (Cámaras de comercio, Alcaldías, RUT, registro mercantil)"
label var 	P6774	"¿... vendería el negocio?"
label var 	P7620	"¿A que actividad se dedicaría?"
label var 	P7630	"¿Cuál es la razón principal por la que ... no vendería el negocio?"
label var 	P7640S1	"¿Cuáles son las dos principales razones por las que trabaja como independiente en lugar de ser empleado?"
label var 	P6750	"¿Cuál fue la ganancia neta o los honorarios netos de ... esa actividad, negocio, profesión o finca, el mes pasado ?"
label var 	P6760	"¿ A cuántos meses corresponde lo que recibió?"
label var 	P550	"¿Cuál fue la ganancia neta del negocio o de la cosecha durante los últimos doce meses?"
label var 	P6782	"¿Aceptaría ... un empleo asalariado con prestaciones, aunque le paguen menos de lo que gana actualmente?"
label var 	P6784	"¿Y si le pagan lo mismo que gana ahora pero con prestaciones, aceptaría un empleo asalariado?"
label var 	P7740	"¿Trabajó alguna vez como asalariado con prestaciones, en su ocupación principal, por lo menos un año?"
label var 	P7750	"¿Cuándo fue la ultima vez que trabajó como asalariado con prestaciones?"
label var 	P7760	"¿Cuál fue la razón principal por la que se terminó este trabajo?"
label var 	P7770	"¿Trabajó alguna vez como asalariado sin prestaciones, en su ocupación principal, por lo menos un año?"
label var 	P7780	"¿Cuándo fue la ultima vez que trabajó como asalariado sin prestaciones?"
label var 	P7790	"¿Cuál fue la razón principal por la que se terminó este trabajo?"
label var 	P6790	"¿Cuántos meses trabajó en los últimos 12 meses?"
label var 	P6800	"¿Cuántas horas a la semana trabaja normalmente.... en ese trabajo ?"
label var 	P6810	"¿Cuál es la razón por la que trabaja normalmente menos de 40 horas a la semana?"
label var 	P6850	"¿Cuántas horas trabajó durante la semana pasada en este trabajo?"
label var 	P6830	"¿Por qué razón, de las horas que normalmente trabaja,  hubo algunas que no trabajo la semana pasada  ?"
label var 	P6835	"¿En que horario realizó su  trabajo principal de la semana pasada ?"
label var 	P6870	"¿Cuántas personas en total tiene la empresa, negocio, industria, oficina, firma, finca o sitio donde ..... trabaja?"
label var 	P6880	"Dónde realiza principalmente su trabajo:"
label var 	P6895	"Por el trabajo principal, ¿ ... paga directamente o le descuentan parte del sueldo para una Entidad Promotora de Salud (EPS)?"
label var 	P6900	"¿Por qué  razón ..... no paga ni le descuentan para el sistema de seguridad social en salud?"
label var 	P6910	"¿En caso de enfermedad como cubriría los costos  médicos y los medicamentos?"
label var 	P6920	"¿Está... cotizando actualmente a un fondo de pensiones?"
label var 	P6930	"¿A cual de los siguientes fondos cotiza actualmente:"
label var 	P6940	"¿ Quién paga mensualmente por la afiliación al fondo de pensiones de...?"
label var 	P6950	"¿Cuánto paga o cuánto le descuentan mensualmente?"
label var 	P6960	"¿Cuántos años lleva cotizando al fondo de pensiones?"
label var 	P6970	"¿En este trabajo, porque razón principal no cotiza, ni le descuentan para obtener una pensión cuando se jubile?"
label var 	P6980S1	"¿Qué está haciendo Usted actualmente para mantenerse económicamente en su vejez?"
label var 	P6990	"¿Está afiliado por una empresa o individualmente a una Aseguradora de Riesgos Profesionales (ARP) (por accidentes de trabajo, enfermedad profesional etc)? "
label var 	P7000	"¿En los últimos doce meses, tuvo Usted alguna enfermedad profesional o un accidente de trabajo que le impidió realizar su trabajo?"
label var 	P7019	"¿En los últimos doce meses, ha recibido pagos por accidente de trabajo o enfermedades profesionales?"
label var 	P7020	"Antes del actual trabajo,  ¿... tuvo otro trabajo?"
label var 	P7022	"En el trabajo anterior ¿ ..... pagaba directamente o le descontaban parte del sueldo para una Entidad Promotora de Salud (EPS)?"
label var 	P7024	"En el trabajo anterior, ¿le descontaban parte del  sueldo o cotizaba a un fondo de pensiones para su jubilación?"
label var 	P7026	"¿Cuánto tiempo duró en su empleo anterior?"
label var 	P7028	"¿En su empleo anterior ..... era:"
label var 	P7040	"Además de la ocupación principal,  ¿.... tenía la semana  pasada otro trabajo o negocio?"
label var 	P7045	"¿Cuántas horas trabajó ... la semana pasada en ese segundo trabajo?"
label var 	P7050	"En ese segundo trabajo…..es: "
label var 	P7070	"¿Cuánto recibió o ganó ….. el mes pasado en ese segundo trabajo o negocio?"
label var 	P7080	"¿Cuál fue el total de los ingresos recibidos o ganados por concepto de todos los trabajos que tuvo durante los últimos doce meses?"
label var 	P7090	"Además de las horas que trabaja actualmente  ¿...... quiere  trabajar más horas?"
label var 	P7100	"¿Cuántas horas adicionales puede trabajar....... a la semana?"
label var 	P7110	"Durante las ÚLTIMAS 4 SEMANAS, ¿ ...... hizo diligencias para trabajar más horas?"
label var 	P7120	"Si la semana pasada le hubiera resultado la posibilidad de trabajar más horas   ¿ estaba...... disponible para hacerlo?"
label var 	P7130	"¿......desea cambiar el trabajo que tiene actualmente?"
label var 	     P7140S1	"¿Por que motivos ....... desea cambiar de trabajo o empleo:"
label var 	P7150	"Durante las ÚLTIMAS 4 SEMANAS,   ¿...... hizo diligencias para  cambiar de trabajo?"
label var 	P7160	"Si le resultara un nuevo trabajo o empleo a...¿podría  empezar a desempeñarlo antes de un mes?"
label var 	     P7170S1	"¿Está .....: muy satisfecho, satisfecho o nada satisfecho:"
label var 	P7180	"¿Está afiliado o hace parte de una asociación gremial o sindical?"
label var 	P7190	"¿Cómo considera que es su empleo o trabajo actual:"
label var 	P7200	"¿Su horario de trabajo y sus responsabilidades familiares son:"
label var 	P7240	"¿En caso de no tener trabajo, de donde obtendría principalmente los recursos para sus gastos y/o los de su hogar:"
