*vivienda
label var	pesoan	"expansor del año"
label var	pesosem	"expansor del semestre"
label var	pesotri	"expansor del trimestre"
label var	c1	"tipo de vivienda"
label var	c2	"material predominante de paredes externas"
label var	c3	"material predominante del techo"
label var	c4	"material predominante de pisos"
label var	c5	"numero de hogares en la vivienda "
label var	d7_1	"tenencia de la vivienda"
label var	d7_2	"tenencia de la vivienda"
label var	d7_3	"tenencia de la vivienda"
label var	d8	"habitaciones residenciales"
label var	d9	"habitaciones para dormir"
label var	d10	"origen del agua"
label var	d11	"control de potabilidad del agua"
label var	d12	"tratamiento del agua"
label var	d13	"llegada de agua"
label var	d14	"servicio sanitario"
label var	d15	"cantidad de baños"
label var	d16	"uso del baño"
label var	d17	"evacuación del servicio sanitario"
label var	d18_1	"fuente de energía para iluminar"
label var	d18_2	"fuente de energía para iluminar"
label var	d18_3	"fuente de energía para iluminar"
label var	d19	"lugar para cocinar"
label var	d20	"fuente de energía para cocinar"
label var	d21_1_1	"elementos de confort"
label var	d21_1_2	"elementos de confort"
label var	d21_1_3	"elementos de confort"
label var	d21_2_1	"elementos de confort"
label var	d21_2_2	"elementos de confort"
label var	d21_3	"elementos de confort"
label var	d21_4	"elementos de confort"
label var	d21_5_1	"elementos de confort"
label var	d21_5_2	"elementos de confort"
label var	d21_6	"elementos de confort"
label var	d21_7	"elementos de confort"
label var	d21_8	"elementos de confort"
label var	d21_9	"elementos de confort"
label var	d21_10	"elementos de confort"
label var	d21_11	"elementos de confort"
label var	d21_12	"elementos de confort"
label var	d21_13	"elementos de confort"
label var	d21_14_1	"elementos de confort"
label var	d21_14_2	"elementos de confort"
label var	d21_15	"elementos de confort"
label var	d21_16_1	"elementos de confort"
label var	d21_16_2	"elementos de confort"
label var	d21_17_1	"elementos de confort"
label var	d21_17_2	"elementos de confort"
label var	d21_18_1	"elementos de confort"
label var	d21_18_2	"elementos de confort"
label var	d21_19_1	"elementos de confort"
label var	d21_19_2	"elementos de confort"
label var	d22	"servicio doméstico"
label var	d23	"personas de 14 o mas años"
label var	d24	"menores de 14 años"
label var	d25	"total de personas del hogar"
label var	h149_1	"recibe dinero de algun familiar u otro hogar en el pais"
label var	h149_2	"recibe dinero de algun familiar u otro hogar en el pais"
label var	h150_1	"recibe ayuda en especie de algun familiar u otro hogar en el pais"
label var	h150_2	"recibe ayuda en especie de algun familiar u otro hogar en el pais"
label var	h151_1	"propietarios de la vivienda"
label var	h152	"propietario de otra vivienda o local"
label var	h153_1	"fueron alquiladas "
label var	h154	"propietario de chacra o campo en el que no trabaja"
label var	h155	"fueron arrendados"
label var	h156_1	"recibio por arrendamiento"
label var	h157	"recibio por medianeria"
label var	h158	"recibio por pastoreo"
label var	h159	"recibio por ganado a capitalizacion"
label var	h160	"recibio intereses por depositos, letras, bonos, prestamos a terceros, etc."
label var	h161_1	"recibio por intereses"
label var	h162	"propietario de negocio en el que no trabaja"
label var	h163_1	"recibio por utilidades y dividendos de algun negocio"
label var	h164_1	"recibio indemnizacion por despido"
label var	h165_1	"recibio alguna colaboración económica de algun familiar en el exterior"
label var	h166_1	"recibio algun ingreso extraordinario"
label var	h167	"hogar inscripto en programa social (panes)"
label var	h168	"hogar visitado por encuestador del panes"
label var	h169	"hogar recibio prestacion por ingreso ciudadano del panes"
label var	h170	"hogar recibio apoyo alimentario del panes"
label var	i171	"pago por contribuciones por divorcio o separacion"
label var	i172	"pago por otras ayudas familiares contribuciones a otros hogares"
label var	ht1	"cantidad de hombres"
label var	ht2	"cantidad de mujeres"
label var	ht3	"cantidad de menores de 14 años"
label var	ht4	"cantidad de mayores de 60 años"
label var	ht5	"cantidad de ocupados"
label var	ht6	"cantidad de desocupados"
label var	ht7	"cantidad de desocupados propiamente dichos"
label var	ht8	"cantidad de desoc. buscan trab. 1a. vez"
label var	ht9	"cantidad de inactivos"
label var	ht10	"cantidad de servicio doméstico"
/*
label var	ht11	"ingreso del hogar c.v.l sin s.s.d"
label var	ht12	"ingreso del servicio doméstico"
label var	ht13	"valor locativo"
label var	ht14	"valor del alquiler"
label var	ht15	"ingreso del jefe del hogar"
label var	ht16	"ingreso del conyuge"
label var	ht17	"ingresos de otros miembros del hogar"
label var	ht19	"cantidad de personas sin servicio doméstico"
label var	ht20	"cantidad de personas perceptores de ingreso"
label var	yciudadano	"ingreso ciudadano"
label var	yhogar	"ingreso del hogar con valor locativo (sin servicio doméstico)"
*/
*personas
label var 	anio	"año de la encuesta"
label var 	correlativ	"identificacion del cuestionario"
label var 	dpto	"departamento"
label var 	nomdpto	"nombre del departamento"
label var 	secc	"seccion censal"
label var 	segm	"segmento censal"
label var 	loc	"localidad"
*label var 	nomloc	"nombre de la localidad"
label var 	ccz	"centro comunal zonal"
label var 	barrio	"barrio"
label var 	nombarrio	"nombre del barrio"
label var 	mes	"mes de la encuesta"
label var 	estrato	"estrato"
label var 	pesoan	"expansor del año"
label var 	pesosem	"expansor del semestre"
label var 	pesotri	"expansor del trimestre"
label var 	nper	"número de persona"
label var 	e26	"sexo"
label var 	e27	"edad"
label var 	e28	"cedula de identidad"
label var 	e29_1	"(mayores de 6 años)   religion"
*label var 	e29_2	"(mayores de 6 años)   religion"
label var 	e30_1	"ascendencia"
label var 	e30_2	"ascendencia"
label var 	e30_3	"ascendencia"
label var 	e30_4	"ascendencia"
label var 	e30_5_1	"ascendencia"
*label var 	e30_5_2	"ascendencia"
label var 	e30_6	"ascendencia"
label var 	e31	"relacion de parentesco"
label var 	e32	"madre del jefe"
label var 	e33	"padre del jefe"
label var 	e34	"(14 y mas años) conyuge o pareja en el hogar"
label var 	e35	"numero de persona"
label var 	e36	"tipo de union"
label var 	e37	"estado civil"
label var 	e38	"hijos nacidos vivos"
label var 	e39_1	"hijos nacidos vivos"
label var 	e39_2	"hijos nacidos vivos"
label var 	e39_3	"hijos nacidos vivos"
label var 	e39_4	"hijos nacidos vivos"
label var 	e39_5	"hijos nacidos vivos"
label var 	e40_1	"(mujeres entre 14_49 años)  primer y ultimo hijo nacido vivo"
label var 	e40_2	"(mujeres entre 14_49 años)  primer y ultimo hijo nacido vivo"
label var 	e41_1	"(mujeres entre 14_49 años)  primer y ultimo hijo nacido vivo"
label var 	e41_2	"(mujeres entre 14_49 años)  primer y ultimo hijo nacido vivo"
label var 	e42_1	"derechos vigentes de salud"
label var 	e42_2	"derechos vigentes de salud"
label var 	e42_3	"derechos vigentes de salud"
label var 	e42_4	"derechos vigentes de salud"
label var 	e42_5	"derechos vigentes de salud"
label var 	e42_6	"derechos vigentes de salud"
label var 	e42_7	"derechos vigentes de salud"
label var 	e42_8	"derechos vigentes de salud"
label var 	e42_9	"derechos vigentes de salud"
label var 	e42_10	"derechos vigentes de salud"
label var 	e42_11_1	"derechos vigentes de salud"
*label var 	e42_11_2	"derechos vigentes de salud"
label var 	e43_1	"atención de la salud"
*label var 	e43_2	"atención de la salud"
label var 	e44_1	"quien paga la cuota mutual"
label var 	e44_2	"quien paga la cuota mutual"
label var 	e45	"afiliacion a emergencia movil"
label var 	e46_1	"quien paga la cuota de la emergencia movil"
label var 	e46_2	"quien paga la cuota de la emergencia movil"
label var 	e47	"sabe leer y escribir"
label var 	e48	"asistencia actual a establecimiento de enseñanza"
label var 	e49	"establecimiento público o privado"
label var 	e50_1	"nivel y año que cursa"
label var 	e50_2	"nivel y año que cursa"
label var 	e50_3	"nivel y año que cursa"
label var 	e50_4	"nivel y año que cursa"
label var 	e50_5	"nivel y año que cursa"
label var 	e50_6	"nivel y año que cursa"
label var 	e50_7	"nivel y año que cursa"
label var 	e50_8	"nivel y año que cursa"
label var 	e50_9	"nivel y año que cursa"
label var 	e50_10	"nivel y año que cursa"
label var 	e50_11	"nivel y año que cursa"
label var 	e50_12	"nivel y año que cursa"
label var 	e51	"asistencia alguna vez a un establecimiento de enseñanza"
label var 	e52_1_1	"nivel y año mas alto alcanzado"
label var 	e52_1_2	"nivel y año mas alto alcanzado"
label var 	e52_2_1	"nivel y año mas alto alcanzado"
label var 	e52_2_2	"nivel y año mas alto alcanzado"
label var 	e52_3_1	"nivel y año mas alto alcanzado"
label var 	e52_3_2	"nivel y año mas alto alcanzado"
label var 	e52_3_3	"nivel y año mas alto alcanzado"
label var 	e52_4_1	"nivel y año mas alto alcanzado"
label var 	e52_4_2	"nivel y año mas alto alcanzado"
label var 	e52_5_1	"nivel y año mas alto alcanzado"
label var 	e52_5_2	"nivel y año mas alto alcanzado"
label var 	e52_6_1	"nivel y año mas alto alcanzado"
label var 	e52_6_2	"nivel y año mas alto alcanzado"
label var 	e52_7_1	"nivel y año mas alto alcanzado"
label var 	e52_7_2	"nivel y año mas alto alcanzado"
*label var 	e53_1	"curso o carrera que estudia/estudió"
label var 	e53_2	"curso o carrera que estudia/estudió"
label var 	e54	"años cursados en enseñanza media"
label var 	e55	"años aprobados en liceo público"
label var 	e56	"años cursados en enseñanza primaria"
label var 	e57	"años aprobados en escuela pública"
label var 	e58_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_1_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_1_2	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_1_3	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_1_4	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_2	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_2_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_2_2	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_2_3	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_2_4	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_3	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_3_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_3_2	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_3_3	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_3_4	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_4	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_4_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_4_2	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_4_3	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_4_4	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_5	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_5_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_5_2	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_5_3	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_5_4	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_6	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_6_1	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_6_2	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_6_3	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_6_4	"concurrencia a comedor o merendero gratuito "
label var 	e58_2_7	"concurrencia a comedor o merendero gratuito "
label var 	e59_1	"recibe algún tipo de alimentación de algún programa público (salvo canastas)"
label var 	e59_2	""
label var 	e59_3	""
label var 	e60	"recibe algún tipo de canasta"
label var 	e60_1_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_1_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_2_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_2_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_3_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_3_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_4_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_4_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_5_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_5_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_6_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_6_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_7_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_7_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_8_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_8_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_9_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_9_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_10_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_10_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_11_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_11_2	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_12_1	"cuales/cuantas canastas recibe mensualmente"
label var 	e60_12_2	"cuales/cuantas canastas recibe mensualmente"
*label var 	e60_12_3	"cuales/cuantas canastas recibe mensualmente"
label var 	e61	"inscripcion a algún programa público de crédito o ayuda para la vivienda"
label var 	f62	"(14 o mas años)                                                                                                                           trabajó por lo menos 1 hora"
label var 	f63	"trabajo en casa o ayuda en negocio, cuidado de animales, cultivos o huerta"
label var 	f64	"trabajo al que volverá"
label var 	f65	"motivo por el cual no trabajó"
label var 	f66	"trabajos que tiene"
*label var 	f67_1	"tareas que proporcionan mayores ingresos"
label var 	f67_2	"tareas que proporcionan mayores ingresos"
*label var 	f68_1	"a que se dedica el establecimiento donde realiza las tareas"
label var 	f68_2	"a que se dedica el establecimiento donde realiza las tareas"
label var 	f69	"categoría de la ocupación"
label var 	f70	"sector publico"
label var 	f71	"tipo de contrato"
label var 	f72	"establecimiento donde realiza tareas pertenece a empresa que lo contrata"
*label var 	f73_1	"a que se dedica la empresa que lo contrata"
label var 	f73_2	"a que se dedica la empresa que lo contrata"
label var 	f74	"tiene derecho a aguinaldo"
label var 	f75	"tamaño  de la empresa "
label var 	f76	"donde realiza su trabajo"
label var 	f77_1	"trabajo en el departamento"
*label var 	f77_2	"trabajo en el departamento"
label var 	f78	"aporte a caja de jubilaciones"
label var 	f79	"a cual aporta"
label var 	f80	"aporte por totalidad del salario"
label var 	f81	"horas trabajadas por semana"
label var 	f82_1	"tiempo que trabaja en forma continua"
label var 	f82_2	"tiempo que trabaja en forma continua"
label var 	f83	"cambio de ocupación en los ultimos tres años"
label var 	f84	"estuvo desocupado en los ultimos 12 meses"
*label var 	f85_1	"tareas que realiza en el otro trabajo"
label var 	f85_2	"tareas que realiza en el otro trabajo"
*label var 	f86_1	"a que se dedica el establecimiento donde realiza las tareas"
label var 	f86_2	"a que se dedica el establecimiento donde realiza las tareas"
label var 	f87	"categoría de la ocupación"
label var 	f88	"tamaño  de la empresa "
label var 	f89_1	"trabajo en el departamento"
label var 	f89_2	"trabajo en el departamento"
label var 	f90	"tiene derecho a aguinaldo"
label var 	f91	"aporte a caja de jubilaciones"
label var 	f92	"a cual aporta"
label var 	f93	"cuantas horas trabaja en otras ocupaciones"
label var 	f94	"busca otro trabajo"
label var 	f95	"sustituir o complementar el actual"
label var 	f96	"razones por las cuales quiere otro empleo"
label var 	f97	"desea trabajar mas horas"
label var 	f98	"esta disponible para trabajar mas horas"
label var 	f99	"razones por las cuales no trabaja mas horas a la semana"
label var 	f100	"que hizo para trabajar más horas"
label var 	f101	"disponibilidad para trabajar"
label var 	f102	"la semana pasada busco trabajo"
label var 	f103	"razones por las cuales no busco trabajo ni establecio su negocio"
label var 	f104	"busco trabajo en las ultimas cuatro  semanas"
label var 	f105	"que hizo para buscar trabajo o establecer su negocio"
label var 	f106	"busca trabajo con condiciones especiales"
label var 	f107	"principal condición que requiere"
label var 	f108	"tiempo que hace que busca trabajo"
label var 	f109	"realizó gestiones concretas"
label var 	f110	"realizó algún trabajo ocasional"
label var 	f111	"ha trabajado antes"
label var 	f112	"esta en seguro de paro"
label var 	f113_1	"tiempo que hace que dejo el ultimo empleo"
label var 	f113_2	"tiempo que hace que dejo el ultimo empleo"
*label var 	f114_1	"tareas que realizaba en esa ocupacion"
label var 	f114_2	"tareas que realizaba en esa ocupacion"
*label var 	f115_1	"a que se dedicaba o que producia el establecimiento en que realizaba sus tareas"
label var 	f115_2	"a que se dedicaba o que producia el establecimiento en que realizaba sus tareas"
label var 	f116	"categoría de la ocupación"
label var 	f117	"razones por lac cuales dejó el trabajo"
label var 	f118	"aportaba a caja de jubilaciones"
label var 	f119_1	"condición de actividad"
label var 	f119_2	"condición de actividad"
label var 	f119_3	"condición de actividad"
label var 	f119_4	"condición de actividad"
label var 	f119_5	"condición de actividad"
label var 	f120	"tipo de pensión que recibe"
label var 	g121_1	"sueldo o jornales líquidos"
label var 	g121_2	"comisiones, incentivos, horas extras"
label var 	g121_3	"viáticos no sujetos a rendición"
label var 	g121_4	"propinas"
label var 	g121_5	"aguinaldo"
label var 	g121_6	"salario vacacional"
label var 	g121_7	"pagos atrasados"
label var 	g121_8	"boletos de transporte"
label var 	g122_1	"recibio alimentos o bebidas"
label var 	g122_2	"recibio alimentos o bebidas"
label var 	g122_3	"recibio alimentos o bebidas"
label var 	g122_4	"recibio alimentos o bebidas"
label var 	g123_1	"recibio tickets de alimentacion"
label var 	g123_2	"recibio tickets de alimentacion"
label var 	g124_1	"recibio vivienda o alojamiento"
label var 	g124_2	"recibio vivienda o alojamiento"
label var 	g124_3	"recibio vivienda o alojamiento"
label var 	g125_1	"recibio cuotas mutuales no declaradas en el sueldo"
label var 	g125_2	"recibio cuotas mutuales no declaradas en el sueldo"
label var 	g126_1	"recibio otro tipo de retribución en especie"
label var 	g126_2	"recibio otro tipo de retribución en especie"
label var 	g127_1	"recibio algun otro tipo de componente pagado por el empleador"
label var 	g127_2	"recibio algun otro tipo de componente pagado por el empleador"
label var 	g128_1	"derecho a pastoreo"
label var 	g128_2	"derecho a pastoreo"
label var 	g128_3	"derecho a pastoreo"
label var 	g128_4	"derecho a pastoreo"
label var 	g129_1	"derecho a cultivo para propio consumo"
label var 	g129_2	"derecho a cultivo para propio consumo"
label var 	g130_1	"sueldo o jornales líquidos"
label var 	g130_2	"comisiones, incentivos, horas extras"
label var 	g130_3	"viáticos no sujetos a rendición"
label var 	g130_4	"propinas"
label var 	g130_5	"aguinaldo"
label var 	g130_6	"salario vacacional"
label var 	g130_7	"pagos atrasados"
label var 	g130_8	"boletos de transporte"
label var 	g131_1	"recibio alimentos o bebidas"
label var 	g131_2	"recibio alimentos o bebidas"
label var 	g131_3	"recibio alimentos o bebidas"
label var 	g131_4	"recibio alimentos o bebidas"
label var 	g132_1	"recibio tickets de alimentacion"
label var 	g132_2	"recibio tickets de alimentacion"
label var 	g133_1	"recibio vivienda o alojamiento"
label var 	g133_2	"recibio vivienda o alojamiento"
label var 	g133_3	"recibio vivienda o alojamiento"
label var 	g134_1	"recibio cuotas mutuales no declaradas en el sueldo"
label var 	g134_2	"recibio cuotas mutuales no declaradas en el sueldo"
label var 	g135_1	"recibio otro tipo de retribución en especie"
label var 	g135_2	"recibio otro tipo de retribución en especie"
label var 	g136_1	"recibio algun otro tipo de componente pagado por el empleador"
label var 	g136_2	"recibio algun otro tipo de componente pagado por el empleador"
label var 	g137_1	"derecho a pastoreo"
label var 	g137_2	"derecho a pastoreo"
label var 	g137_3	"derecho a pastoreo"
label var 	g137_4	"derecho a pastoreo"
label var 	g138_1	"derecho a cultivo para propio consumo"
label var 	g138_2	"derecho a cultivo para propio consumo"
label var 	g139	"retiro realizado para gastos del hogar"
label var 	g140	"distribución de utilidades"
label var 	g141_1	"retiro de productos para consumo propio (trabajador no agropecuario)"
label var 	g141_2	"retiro de productos para consumo propio (trabajador no agropecuario)"
label var 	g141_3	"retiro de productos para consumo propio (trabajador agropecuario)"
label var 	g141_4	"retiro de productos para consumo propio (trabajador agropecuario)"
label var 	g141_5	"retiro de productos para consumo propio (trabajador agropecuario)"
label var 	g141_6	"retiro de productos para consumo propio (trabajador agropecuario)"
label var 	g141_7	"retiro de productos para consumo propio (trabajador agropecuario)"
label var 	g142	"recibio por medianeria o parceria"
label var 	g143	"recibio por pastoreo"
label var 	g144	"recibio por ganado a capitalización"
label var 	g145_1	"jubilaciones_bps-caja industria y comercio"
label var 	g145_2	"jubilaciones_bps-caja civil y escolar"
label var 	g145_3	"jubilaciones_bps-rural y servicio doméstico"
label var 	g145_4	"jubilaciones_unión postal"
label var 	g145_5	"jubilaciones_policial"
label var 	g145_6	"jubilaciones_militar"
label var 	g145_7	"jubilaciones_profesional"
label var 	g145_8	"jubilaciones_notarial"
label var 	g145_9	"jubilaciones_bancaria"
label var 	g145_10	"jubilaciones_otra "
label var 	g145_11	"jubilaciones_otro país"
label var 	g145_12	"pensiones_bps-caja industria y comercio"
label var 	g145_13	"pensiones_bps-caja civil y escolar"
label var 	g145_14	"pensiones_bps-rural y servicio doméstico"
label var 	g145_15	"pensiones_unión postal"
label var 	g145_16	"pensiones_policial"
label var 	g145_17	"pensiones_militar"
label var 	g145_18	"pensiones_profesional"
label var 	g145_19	"pensiones_notarial"
label var 	g145_20	"pensiones_bancaria"
label var 	g145_21	"pensiones_otra"
label var 	g145_22	"pensiones_otro país"
label var 	g145_23	"seguro de desempleo"
label var 	g145_24	"compensaciones por accidente, maternidad o enfermedad"
label var 	g145_25	"becas, subsidios, donaciones"
label var 	g145_26	"becas, subsidios, donaciones"
label var 	g146_1	"cobra hogar constituido"
label var 	g146_2	"cobra hogar constituido"
label var 	g147_1	"cobra asignaciones familiares"
label var 	g147_2	"cobra asignaciones familiares"
label var 	g147_3	"cobra asignaciones familiares"
label var 	g147_4	"cobra asignaciones familiares"
label var 	g148_1	"recibe pensión alimenticia o alguna contribución por divorcio o separación"
label var 	g148_2	"recibe pensión alimenticia o alguna contribución por divorcio o separación"
label var 	g148_3	"recibe pensión alimenticia o alguna contribución por divorcio o separación"
label var 	pobpcoac	"condicion de actividad economica"
label var 	mto_cuota	"cuota mutual"
label var 	mto_hogcon	"hogar constituido"
label var 	mto_desay	"monto desayuno o merienda"
label var 	mto_almue	"monto almuerzo"
label var 	mto_vacas	"vaca de pastoreo"
label var 	mto_oveja	"oveja de pastoreo"
label var 	mto_caball	"caballo de pastoreo"
/*
label var 	pt1	"total de ingresos corrientes"
label var 	ytdop	"total de ingresos del trabajador dependiente"
label var 	ytdos	"total de ingresos del trabajador dependiente"
label var 	ytinde	"ingreso del trabajador no dependiente"
label var 	ytransf	"ingreso por transferencias"
label var 	pt2	"ingreso por ocupacion principal"
label var 	pt2priv	"empleado privado"
label var 	pt2pub	"empleado publico/programa publico de empleo"
label var 	pt2nodep	"trabajador no dependiente"
label var 	pt4	"total de ingresos por trabajo"
*/
label var 	subempleo	"trabajador subempleado "
label var 	indacomun	"inda comun (riesgo social)"
label var 	indabajo	"inda bajo peso (riesgo nutricional)"
label var 	indaplomo	"inda contaminacion por plomo"
label var 	indapensi	"pensionistas"
label var 	indadiabet	"diabeticos"
label var 	indarenal	"renales"
label var 	indarendia	"renales-diabeticos"
label var 	indaceliac	"celiacos"
label var 	indatuberc	"tuberculosis"
label var 	indaoncolo	"oncologicos"
label var 	indasida	"paec hiv"
label var 	otrcanast	"otras"
