dictionary  {
_column(001) tipo_reg                       %2g   "tipo de registro                             "                       
_column(003) cod_uf                         %2g   "código da uf                                 "                       
_column(005) num_seq                        %3g   "número sequencial                            "                       
_column(008) num_dv                         %1g   "dv do sequencial                             "                       
_column(009) cod_domc                       %2g   "número do domicílio                          "                       
_column(011) num_uc                         %1g   "número da uc                                 "                       
_column(012) num_informante                 %2g   "número do informante                         "                       
_column(014) num_ext_renda                  %2g   "estrato geográfico                           "                       
_column(016) fator_expansao1                %14.8g "fator de expansăo 1 (desenho amostral)       "                       
_column(030) fator_expansao2                %14.8g "fator de expansăo 2 (ajustado p/ estimativas)"                       
_column(044) cod_rel_pess_refe_uc           %2g   "condiçăo na unidade de consumo               "                       
_column(046) num_familia                    %2g   "número da família                            "                       
_column(048) cod_cond_familia               %2g   "condiçăo na família                          "                       
_column(050) cod_cond_presenca              %2g   "condiçăo de presença                         "                       
_column(052) dat_dia_nasc                   %2g   "dia de nascimento                            "                       
_column(054) dat_mes_nasc                   %2g   "męs de nascimento                            "                       
_column(056) dat_ano_nasc                   %4g   "ano de nascimento                            "                       
_column(060) idade_anos                     %3g   "idade calculada em anos                      "                       
_column(063) idade_mes                      %6g   "idade calculada em meses                     "                       
_column(069) idade_dia                      %7g   "idade calculada em dias                      "                       
_column(076) cod_sexo                       %2g   "sexo                                         "                       
_column(078) cod_sabe_ler                   %2g   "sabe ler e escrever                          "                       
_column(080) cod_freq_escola                %2g   "frequęncia a escola ou creche                "                       
_column(082) cod_curso_freq                 %2g   "curso que frequenta                          "                     
_column(084) cod_dur_primeiro_grau_eh       %2g   "qual a duraçăo do curso de primeiro grau     "                     
_column(086) cod_serie_freq                 %2g   "série que frequenta                          "                     
_column(088) cod_nivel_instr                %2g   "curso mais elevado que frequentou            "                     
_column(090) cod_dur_primeiro_grau_era      %2g   "qual era a duraçăo do curso de primeiro grau "                       
_column(092) cod_serie_com_aprovacao        %2g   "última serie concluída                       "                       
_column(094) cod_concluiu_curso             %2g   "conclusăo do curso mais elevado              "                       
_column(096) anos_de_estudo                 %2g   "anos de estudo                               "                       
_column(098) cod_cor_raca                   %2g   "cor ou raça                                  "                       
_column(100) cod_sit_receita                %2g   "orçamento trabalho e/ou rendimento           "                       
_column(102) cod_sit_despesa                %2g   "orçamento despesa                            "                      
_column(104) cod_tem_cartao                 %2g   "tem cartăo de crédito                        "                      
_column(106) cod_ehtitular_cartao           %2g   "titular do cartăo de crédito                 "                      
_column(108) cod_tem_cheque                 %2g   "tem cheque especial                          "                      
_column(110) cod_ehtitular_conta            %2g   "titular da conta corrente                    "                    
_column(112) renda_bruta_monetaria          %16.2g  "renda monetária mensal da uc                 "                    
_column(128) renda_bruta_nao_monetaria      %16.2g  "renda năo-monetária mensal da uc             "                    
_column(144) renda_total                    %16.2g  "renda total mensal da uc                     "                     
_column(160) cod_gravida                    %2g   "está grávida                                 "
_column(162) num_comprimento                %5.1g   "comprimento original                         "
_column(167) num_altura                     %5.1g   "altura original                              "
_column(172) num_peso                       %5.1g   "peso original                                "
_column(177) num_peso_crianca               %5.1g   "peso original das crianças                   "
_column(182) comprimento_imputado           %5.1g   "comprimento imputado                         "
_column(187) altura_imputado                %5.1g   "altura imputada                              "
_column(192) peso_imputado                  %5.1g   "peso imputado                                "
_column(197) renda_percapita                %16.2g  "renda per capita da uc                       "  
_column(213) cod_religiao                   %8g   "código da religiao                           "
_column(221) cod_tem_plano                  %2g   "tem plano de saúde                           "
_column(223) cod_ehtitular                  %2g   "é titular do plano de saúde                  "
_column(225) cod_num_dependente             %2g   "número de dependentes do plano de saúde      "
_column(227) cod_unid_consumo               %2g   "código da unidade de consumo alimentar       "
_column(229) teve_necessidade_medicamento   %2g   "teve necessidade de medicamento              "
_column(231) precisou_algum_servico         %2g   "precisou de algum serviço de saúde           "
_column(233) tempo_gestacao                 %2g   "tempo de gestaçăo                            "
_column(235) cod_amamentando                %2g   "está amamentando                             "
_column(237) cod_leite_materno              %2g   "recebimento de leite materno                 "
_column(239) cod_outro_alimento             %2g   "recebimento de outro tipo de alimento        "
_column(241) meses_leite_materno            %2g   "número de meses que recebeu leite materno    "
_column(243) cod_freq_alimentar             %2g   "frequęncia alimentar na escola               "
_column(245) cod_alimento_consumido         %2g  "alimentos consumidos na escola               "
}
