dictionary  {
_column(001) str2 tipo_reg                       %2s   "tipo de registro                             "                       
_column(003) str2 cod_uf                         %2s   "código da uf                                 "                       
_column(005) str3 num_seq                        %3s   "número sequencial                            "                       
_column(008) str1 num_dv                         %1s   "dv do sequencial                             "                       
_column(009) str2 cod_domc                       %2s   "número do domicílio                          "                        
_column(011) str1 num_uc                         %1s   "número da uc                                 "    
_column(012) str2 num_ord_inform                 %2s   " número do informante                             "   
_column(014) num_ext_renda                  %2g   " estrato geográfico                               "   
_column(016) fator_expansao1                %14.8g  " fator de expansão 1 (desenho amostral)           "   
_column(030) fator_expansao2                %14.8g  " fator de expansão 2 (ajustado p/ estimativas)    "   
_column(044) num_quadro                     %2g   " número do quadro                                 "   
_column(046) str5 cod_item                      %5s   " código do item                                   "   
_column(051) val_recebido                   %11.2g  " valor do rendimento                              "   
_column(062) val_deducao                    %11.2g  " valor da deducao                                 "   
_column(073) cod_deduc                      %5g   " código da dedução                                "   
_column(078) mes_ultimo_rendimento          %2g   " mês do último rendimento                         "   
_column(080) num_meses_resgate              %2g   " número meses recebidos                           "   
_column(082) fator_anual                    %2g   " fator de anualização                             "   
_column(084) num_deflator                   %5.2g  " deflator fator                                   "   
_column(089) val_recebido_corrigido         %11.2g  " valor do rendimento deflacionado                 "   
_column(100) val_deducao_corrigido          %11.2g  " valor da deducao deflacionado                    "   
_column(111) valor_anual_expandido2         %16.2g  " valor da despesa anualizado e expandido (fator2) "   
_column(127) valor_deduc_anual_expandido2   %16.2g  " valor da dedução anualizado e expandido (fator2) "   
_column(143) cod_imput                      %2g   " código de imputação                              "   
_column(145) renda_bruta_monetaria          %16.2g  " renda monetária mensal da uc                     "   
_column(161) renda_bruta_nao_monetaria      %16.2g  " renda não monetária mensal da uc                 "   
_column(177) renda_total                    %16.2g " renda total mensal da uc                         "   
}
