dictionary  {
_column(001) str2 tipo_reg                       %2s   "tipo de registro                             "                       
_column(003) str2 cod_uf                         %2s   "código da uf                                 "                       
_column(005) str3 num_seq                        %3s   "número sequencial                            "                       
_column(008) str1 num_dv                         %1s   "dv do sequencial                             "                       
_column(009) str2 cod_domc                       %2s   "número do domicílio                          "                        
_column(011) str1 num_uc                         %1s   "número da uc                                 "    
_column(012) str2 num_ordem_inform               %2s   " número do informante                                   "   
_column(014) num_ext_renda                  %2g   " estrato geográfico                                     "  
_column(016) fator_expansao1                %14.8g  " fator de expansão 1 (desenho amostral)                 "  
_column(030) fator_expansao2                %14.8g  " fator de expansão 2 (ajustado p/ estimativas)          "  
_column(044) num_quadro                     %2g   " número do quadro                                       "  
_column(046) cod_tipo_ocup                  %1g   " tipo de trabalho                                       "  
_column(047) cod_posi_ocupa                 %2g   " posição na ocupação                                    "  
_column(049) cod_renm_bruto                 %1g   " forma do último rendimento                             "
_column(050) str5 cod_item                       %5s   " código do item                                         "
_column(055) val_renm_bruto                 %11.2g  " valor do último rendimento                             "
_column(066) val_mes                        %2g   " mês do último rendimento                               "
_column(068) num_meses_recebe               %2g   " número de meses recebidos                              "
_column(070) cod_deducao_val                %1g   " existência de dedução                                  "
_column(071) cod_item_prev                  %5g   " código de previdência pública                          "
_column(076) val_deducao_prev               %11.2g  " valor da previdência pública                           "
_column(087) cod_item_ir                    %5g   " código de imposto de renda                             "
_column(092) val_deducao_ir                 %11.2g  " valor do imposto renda                                 "
_column(103) cod_item_outra                 %5g   " código de outras deduções                              "
_column(108) val_deducao_outra              %11.2g  " valor de outras deduções                               "
_column(119) fator_anual                    %2g   " fator de anualização                                   "
_column(121) num_deflator                   %5.2g  " deflator fator                                         "
_column(126) val_renm_bruto_corrigido       %11.2g  " valor do último rendimento deflacionado                "
_column(137) val_deducao_prev_corrigido     %11.2g  " valor da previdência pública deflacionado              "
_column(148) val_deducao_ir_corrigido       %11.2g  " valor do imposto renda deflacionado                    "
_column(159) val_deducao_outra_corrigido    %11.2g  " valor de outras deduções deflacionado                  "
_column(170) valor_anual_expandido2         %16.2g  " valor do último rend. anualizado e expandido (fator2)  "
_column(186) valor_prev_anual_expandido2    %16.2g  " valor da prev. pública anualizado e expandido (fator2) "
_column(202) valor_ir_anual_expandido2      %16.2g  " valor do imp. renda anualizado e expandido (fator2)    "
_column(218) valor_outras_anual_expandido2  %16.2g  " valor de out. deduções anualizado e expandido (fator2) "
_column(234) cod_imput                      %2g   " código de imputação                                    "
_column(236) renda_bruta_monetaria          %16.2g  " renda monetária mensal da uc                           "
_column(252) renda_bruta_nao_monetaria      %16.2g  " renda não monetária mensal da uc                       "
_column(268) renda_total                    %16.2g  " renda total mensal da uc                               "
_column(284) num_horas_trabalhadas          %3g   " número de horas trabalhadas                            "
_column(287) cod_ocup_final                 %8g   " código de ocupação                                     "
_column(295) cod_ativ_final                 %8g   " código de atividade                                    "
_column(303) cod_imput_ocup_ativ            %2g  " código de imputação de ocupação e atividade            "
 
}
